#!/usr/bin/env bash

#
# Exit at any error
#
set -e

#
# Find base dir and go there
#
DIR="$(cd "$(dirname "$0")"; pwd -P)"
cd "${DIR}"

#
# Load library for printing info
#
. ./print

#
# Manage directories
#
if [ ! -d ~/Code ]; then
    info "Creating ~/Code directory" 1
    mkdir ~/Code
    ok
fi

#
# Create symbolic links for all conf files
#
for FILEPATH in $(find conf -type f -not -path "."); do
    NAME=$(basename "${FILEPATH}")
    if [ -h ~/.${NAME} ]; then
        rm ~/.${NAME}
    fi

    if [ -f ~/.${NAME} ]; then
        warn "Skipping ~/.${NAME}. File already exists"
    else
        info "Creating symlink to ~/.${NAME}" 1
        ln -s ${DIR}/${FILEPATH} ~/.${NAME}
        ok
    fi
done
unset FILEPATH

#
# Run all app installs
#
info "Do you want to run app installers [y/n]: " 1
read APPINSTALL
if [ $APPINSTALL = 'y' ] || [ $APPINSTALL = 'Y' ]; then
    for APP in $DIR/apps-mac/*; do
        sudo bash $APP
    done
fi

echo
ok
echo