#!/usr/bin/env bash

#
# Exit at any error
#
set -e

#
# Find base dir and go there
#
DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "${DIR}"

#
# Run installer for current OS
#
if [ "$(uname)" == "Darwin" ]; then
    bash "${DIR}/install-mac"
else
    bash "${DIR}/install-ubuntu"
fi