#!/usr/bin/env bash

#
# Exit at any error
#
set -e

#
# Find base dir and go there
#
DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "${DIR}"

msg() {
	echo -e "\e[0;32m$1\e[0m"
}

#
# Install some required software
#
msg "Install curl and xclip"
export LC_ALL=en_US.UTF-8
sudo apt-get install curl xclip -yq > /dev/null

#
# Create symbolic links for all conf files
#
for FILEPATH in $(find conf -type f -not -path "."); do
	NAME=$(basename "${FILEPATH}")
	if [ -h ~/.${NAME} ]; then
		rm ~/.${NAME}
	fi

	if [ -f ~/.${NAME} ]; then
		msg "Skipping ~/.${NAME}. File already exists"
	else
		msg "Creating symlink ~/.${NAME}"
		ln -s ${DIR}/${FILEPATH} ~/.${NAME}
	fi
done
unset FILEPATH

#
# Manage directories
#
if [ ! -d ~/Code ]; then
	msg "Creating ~/Code directory"
	mkdir ~/Code
fi

if [ -d ~/Templates ]; then
	msg "Deleting ~/Templates directory"
	mkdir ~/Templates
fi

#
# Load bash_profile
#
if ! cat ~/.bashrc | grep -q '. ~/.bash_profile'; then
	msg "Loading .bash_profile by .bashrc"
	echo -e '\n. ~/.bash_profile' >> ~/.bashrc

	echo ''
	echo -e "\e[1;33mRestart terminal\e[0m"
fi

echo ''
echo -e "\e[1;32mDone!\e[0m"
echo ''