#!/usr/bin/env bash

info() {
    echo
    echo -en "\033[0;32m$1 ... \033[0m"
    if [ -z $2 ]; then
        echo
    fi
}
warn() {
    echo -en "\033[1;33m$1\033[0m"
    if [ -z $2 ]; then
        echo
    else
        echo -n ' '
    fi
}
ok() {
    echo -en "\033[1;32mDone! \033[0m"
    if [ -z $1 ]; then
        echo
    fi
}