#!/usr/bin/env bash

info() {
    echo
    echo -en "\e[0;32m$1 ... \e[0m"
    if [ -z $2 ]; then
        echo
    fi
}
warn() {
    echo -en "\e[1;33m$1\e[0m"
    if [ -z $2 ]; then
        echo
    else
        echo -n ' '
    fi
}
ok() {
    echo -en "\e[1;32mDone! \e[0m"
    if [ -z $1 ]; then
        echo
    fi
}