#!/usr/bin/env bash

DIR="$(dirname $(dirname $(dirname "$(readlink "${BASH_SOURCE[0]}")")))"

export PATH="${DIR}/bin:/usr/local/sbin:$PATH"

# Source all bash files
for i in ${DIR}/bash/*; do
    . $i
done
unset i

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
