#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing sudoless access for user ivan"

echo "ivan ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/ivan > /dev/null
sudo chmod 0440 /etc/sudoers.d/*

ok