#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing global locale fix"

if cat /etc/environment | grep -q 'LC_ALL='; then
    echo -e "\e[1;33mAlready installed\e[0m"
    exit 0
fi

echo "LANGUAGE=en_US.UTF-8
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8" | sudo tee -a /etc/environment > /dev/null

export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

ok