#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing support for Apple Keyboard"

if cat /etc/rc.local | grep -q 'hid_apple'; then
    warn "Already installed!"
    exit 0
fi

sudo sed -i '/^exit 0/i \
echo 2 > /sys/module/hid_apple/parameters/fnmode\
echo 0 > /sys/module/hid_apple/parameters/iso_layout\
echo 1 > /sys/module/hid_apple/parameters/swap_opt_cmd\
' /etc/rc.local

ok 1
warn "Restart computer for all changes to take effect. Log out doesn't work!"