#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Git"

if which git; then
    warn "Already installed!"
    exit 0
fi

sudo apt-get install git -yq

ok