#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing wget" 1

if which python3 > /dev/null; then
    warn "Already installed!"
    exit 0
fi

brew install python3

ok