#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Google Chrome"

if which google-chrome > /dev/null; then
    warn "Already installed!"
    exit 0
fi

# TODO

ok