#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Dnsmasq"

if brew ls --versions dnsmasq > /dev/null; then
	warn "Already installed!"
    exit 0
fi

brew install dnsmasq
mkdir -pv $(brew --prefix)/etc/
echo 'conf-dir=/etc/dnsmasq.d/*.conf' > $(brew --prefix)/etc/dnsmasq.conf
sudo mkdir /etc/dnsmasq.d
echo 'address=/.app/192.168.10.10' | sudo tee /etc/dnsmasq.d/app.conf
echo 'address=/.loc/192.168.10.10' | sudo tee /etc/dnsmasq.d/loc.conf
sudo brew services restart dnsmasq

ok
