#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Darktable"

if which darktable > /dev/null; then
	warn "Already installed!"
    exit 0
fi

# TODO

ok