#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Phockup"

if which phockup > /dev/null; then
	warn "Already installed!"
    exit 0
fi

sudo apt-get install libimage-exiftool-perl -y
git clone https://github.com/ivandokov/phockup.git /opt/phockup
sudo ln -s /opt/phockup/phockup.py /usr/local/bin/phockup

ok