#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Dart"

if which dart > /dev/null; then
    warn "Already installed!"
    exit 0
fi

brew install dart
ok
