#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Go"

if which go > /dev/null; then
    warn "Already installed!"
    exit 0
fi

brew install go
ok