#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing MySQL"

if which mysql > /dev/null; then
    warn "Already installed!"
    exit 0
fi

brew install mysql@5.7
ok
