#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Node.js"

if which node > /dev/null; then
    warn "Already installed!"
    exit 0
fi

brew install node
brew install yarn
ok
