#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

if which node > /dev/null; then
    info "Installing node" 1
    brew install node
    brew install yarn
    ok
fi
