#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing sudoless access for user $SUDO_USER" 1

echo "$SUDO_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee -a "/etc/sudoers.d/$SUDO_USER" > /dev/null
sudo chmod 0440 /etc/sudoers.d/*

ok
