#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Google Chrome"

if which google-chrome > /dev/null; then
    warn "Already installed!"
    exit 0
fi

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

sudo dpkg -i google-chrome*.deb
sudo apt-get install -fy
rm google-chrome*.deb

ok