#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Setting up dnsmasq"

echo 'address=/.loc/192.168.10.10
address=/.app/192.168.10.10' | sudo tee /etc/NetworkManager/dnsmasq.d/hosts.conf
warn "Restart computer for hosts configurations to take effect!" 1

ok
