#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Dnsmasq"

if which dnsmasq > /dev/null; then
    warn "Already installed!"
    exit 0
fi

echo 'address=/.app/192.168.10.10
address=/.loc/192.168.10.10' | sudo tee /etc/NetworkManager/dnsmasq.d/loc.conf
sudo service network-manager restart

ok
