#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing PhpStorm"

if which pstorm > /dev/null; then
    warn "Already installed!"
    exit 0
fi

wget https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.3.2421.tar.gz
tar -zxf jetbrains*.tar.gz
rm jetbrains*.tar.gz
mv jetbrains* /opt/toolbox
./opt/jetbrains-toolbox/jetbrains-toolbox

ok
