#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing PhpStorm"

if which pstorm > /dev/null; then
    warn "Already installed!"
    exit 0
fi

wget https://download.jetbrains.com/webide/PhpStorm-2016.3.tar.gz
tar -zxf PhpStorm-2016.*.tar.gz
rm PhpStorm-2016.*.tar.gz
mv PhpStorm-* /opt/phpstorm-2016

ok
