#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Darktable"

if which darktable > /dev/null; then
	warn "Already installed!"
    exit 0
fi

sudo apt-add-repository ppa:pmjdebruijn/darktable-release -y
sudo apt-get update
sudo apt-get install darktable -y

ok