#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Installing Phockup"

if which phockup > /dev/null; then
    warn "Already installed!"
    exit 0
fi

sudo apt-get install snapd -y
sudo snap install phockup

ok
