#!/usr/bin/env bash

DIR="$(dirname $(dirname "${BASH_SOURCE[0]}"))"
. "$DIR/print"

info "Setting up dnsmasq"

echo 'address=/.loc/127.0.0.1
address=/.loc/127.0.0.1' | sudo tee /etc/NetworkManager/dnsmasq.d/loc.conf
warn "Restart computer for hosts configurations to take effect!" 1

ok
